apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  ports:
  - port: 15672
#    nodePort: 11201
    targetPort: vpromq01-port
    protocol: TCP
  selector:
    app: vpromq01 
  type: ClusterIP
